# Generated by Django 2.2.7 on 2019-11-26 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0003_urlsite'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='support_level',
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, default=None, null=True),
        ),
    ]
