# Generated by Django 2.2.7 on 2019-11-26 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0004_call_support_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='call',
            old_name='support_level',
            new_name='rating',
        ),
    ]
